<?php

namespace DoctrineProxies\__CG__\App\Models\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class tbParametros extends \App\Models\Entity\tbParametros implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'Id', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'dthrSincronizacao', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'diasReenvioTicket', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'diasConclusaoTicket', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'mensagemReenvio', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'mensagemReenvio2', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'mensagemConclusao', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'codCliNconcl'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'Id', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'dthrSincronizacao', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'diasReenvioTicket', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'diasConclusaoTicket', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'mensagemReenvio', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'mensagemReenvio2', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'mensagemConclusao', '' . "\0" . 'App\\Models\\Entity\\tbParametros' . "\0" . 'codCliNconcl'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (tbParametros $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($Id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$Id]);

        return parent::setId($Id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDthrSincronizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDthrSincronizacao', []);

        return parent::getDthrSincronizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDthrSincronizacao($dthrSincronizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDthrSincronizacao', [$dthrSincronizacao]);

        return parent::setDthrSincronizacao($dthrSincronizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasReenvioTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasReenvioTicket', []);

        return parent::getDiasReenvioTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasReenvioTicket($diasReenvioTicket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasReenvioTicket', [$diasReenvioTicket]);

        return parent::setDiasReenvioTicket($diasReenvioTicket);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiasConclusaoTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiasConclusaoTicket', []);

        return parent::getDiasConclusaoTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiasConclusaoTicket($diasConclusaoTicket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiasConclusaoTicket', [$diasConclusaoTicket]);

        return parent::setDiasConclusaoTicket($diasConclusaoTicket);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensagemReenvio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensagemReenvio', []);

        return parent::getMensagemReenvio();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensagemReenvio($mensagemReenvio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensagemReenvio', [$mensagemReenvio]);

        return parent::setMensagemReenvio($mensagemReenvio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensagemConclusao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensagemConclusao', []);

        return parent::getMensagemConclusao();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensagemConclusao($mensagemConclusao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensagemConclusao', [$mensagemConclusao]);

        return parent::setMensagemConclusao($mensagemConclusao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodCliNconcl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodCliNconcl', []);

        return parent::getCodCliNconcl();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodCliNconcl($codCliNconcl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodCliNconcl', [$codCliNconcl]);

        return parent::setCodCliNconcl($codCliNconcl);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensagemReenvio2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensagemReenvio2', []);

        return parent::getMensagemReenvio2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMensagemReenvio2($mensagemReenvio2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensagemReenvio2', [$mensagemReenvio2]);

        return parent::setMensagemReenvio2($mensagemReenvio2);
    }

}
