<?php

namespace DoctrineProxies\__CG__\App\Models\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class tbUsuarios extends \App\Models\Entity\tbUsuarios implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'codusuario', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'nomecompleto', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'nome', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'sobrenome', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'coddepartamentoint', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'hrregrapainelticket', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'qtddiasatraso', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'metahrconclticket', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'ativo', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'codticket', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'gerente'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'codusuario', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'nomecompleto', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'nome', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'sobrenome', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'coddepartamentoint', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'hrregrapainelticket', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'qtddiasatraso', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'metahrconclticket', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'ativo', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'codticket', '' . "\0" . 'App\\Models\\Entity\\tbUsuarios' . "\0" . 'gerente'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (tbUsuarios $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setcodticket(\App\Models\Entity\tbTickets $codticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcodticket', [$codticket]);

        return parent::setcodticket($codticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodticket(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodticket', []);

        return parent::getCodticket();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodusuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodusuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodusuario', []);

        return parent::getCodusuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodusuario($codusuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodusuario', [$codusuario]);

        return parent::setCodusuario($codusuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomecompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomecompleto', []);

        return parent::getNomecompleto();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomecompleto($nomecompleto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomecompleto', [$nomecompleto]);

        return parent::setNomecompleto($nomecompleto);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getSobrenome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSobrenome', []);

        return parent::getSobrenome();
    }

    /**
     * {@inheritDoc}
     */
    public function setSobrenome($sobrenome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSobrenome', [$sobrenome]);

        return parent::setSobrenome($sobrenome);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoddepartamentoint()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoddepartamentoint', []);

        return parent::getCoddepartamentoint();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoddepartamentoint($coddepartamentoint)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoddepartamentoint', [$coddepartamentoint]);

        return parent::setCoddepartamentoint($coddepartamentoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrregrapainelticket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrregrapainelticket', []);

        return parent::getHrregrapainelticket();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrregrapainelticket($hrregrapainelticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrregrapainelticket', [$hrregrapainelticket]);

        return parent::setHrregrapainelticket($hrregrapainelticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtddiasatraso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtddiasatraso', []);

        return parent::getQtddiasatraso();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtddiasatraso($qtddiasatraso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtddiasatraso', [$qtddiasatraso]);

        return parent::setQtddiasatraso($qtddiasatraso);
    }

    /**
     * {@inheritDoc}
     */
    public function getMetahrconclticket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMetahrconclticket', []);

        return parent::getMetahrconclticket();
    }

    /**
     * {@inheritDoc}
     */
    public function setMetahrconclticket($metahrconclticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMetahrconclticket', [$metahrconclticket]);

        return parent::setMetahrconclticket($metahrconclticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtivo', []);

        return parent::getAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtivo($ativo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtivo', [$ativo]);

        return parent::setAtivo($ativo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGerente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGerente', []);

        return parent::getGerente();
    }

    /**
     * {@inheritDoc}
     */
    public function setGerente($gerente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGerente', [$gerente]);

        return parent::setGerente($gerente);
    }

}
